PetsLife/grails-app/domain/petslife/DonoPet.groovy
package petslife

class DonoPet {
    String nome
    String cpf
    int telefone
    
    static constraints = {  
        nome nome:true, unique:true
        cpf cpf:true, unique:true
        telefone telefone:true, unique:true
    }
    
    String toString(){
        nome
    }
}

PetsLife/grails-app/controllers/petslife/DonoPetController.groovy
package petslife



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import org.springframework.security.access.annotation.Secured
@Secured('isFullyAuthenticated()')

@Transactional(readOnly = true)
class DonoPetController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond DonoPet.list(params), model:[donoPetInstanceCount: DonoPet.count()]
    }

    def show(DonoPet donoPetInstance) {
        respond donoPetInstance
    }

    def create() {
        respond new DonoPet(params)
    }

    @Transactional
    def save(DonoPet donoPetInstance) {
        if (donoPetInstance == null) {
            notFound()
            return
        }

        if (donoPetInstance.hasErrors()) {
            respond donoPetInstance.errors, view:'create'
            return
        }

        donoPetInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'donoPet.label', default: 'DonoPet'), donoPetInstance.id])
                redirect donoPetInstance
            }
            '*' { respond donoPetInstance, [status: CREATED] }
        }
    }

    def edit(DonoPet donoPetInstance) {
        respond donoPetInstance
    }

    @Transactional
    def update(DonoPet donoPetInstance) {
        if (donoPetInstance == null) {
            notFound()
            return
        }

        if (donoPetInstance.hasErrors()) {
            respond donoPetInstance.errors, view:'edit'
            return
        }

        donoPetInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'DonoPet.label', default: 'DonoPet'), donoPetInstance.id])
                redirect donoPetInstance
            }
            '*'{ respond donoPetInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(DonoPet donoPetInstance) {

        if (donoPetInstance == null) {
            notFound()
            return
        }

        donoPetInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'DonoPet.label', default: 'DonoPet'), donoPetInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'donoPet.label', default: 'DonoPet'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

PetsLife/grails-app/views/donoPet/_form.gsp
<%@ page import="petslife.DonoPet" %>



<div class="fieldcontain ${hasErrors(bean: donoPetInstance, field: 'nome', 'error')} required">
	<label for="nome">
		<g:message code="donoPet.nome.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nome" required="" value="${donoPetInstance?.nome}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: donoPetInstance, field: 'cpf', 'error')} required">
	<label for="cpf">
		<g:message code="donoPet.cpf.label" default="Cpf" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="cpf" required="" value="${donoPetInstance?.cpf}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: donoPetInstance, field: 'telefone', 'error')} required">
	<label for="telefone">
		<g:message code="donoPet.telefone.label" default="Telefone" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="telefone" type="number" value="${donoPetInstance.telefone}" required=""/>

</div>

PetsLife/grails-app/views/donoPet/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoPet.label', default: 'DonoPet')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-donoPet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-donoPet" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${donoPetInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${donoPetInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:donoPetInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

PetsLife/grails-app/views/donoPet/edit.gsp
<%@ page import="petslife.DonoPet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoPet.label', default: 'DonoPet')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-donoPet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-donoPet" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${donoPetInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${donoPetInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:donoPetInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${donoPetInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

PetsLife/grails-app/views/donoPet/index.gsp
<%@ page import="petslife.DonoPet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoPet.label', default: 'DonoPet')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-donoPet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-donoPet" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nome" title="${message(code: 'donoPet.nome.label', default: 'Nome')}" />
					
						<g:sortableColumn property="cpf" title="${message(code: 'donoPet.cpf.label', default: 'Cpf')}" />
					
						<g:sortableColumn property="telefone" title="${message(code: 'donoPet.telefone.label', default: 'Telefone')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${donoPetInstanceList}" status="i" var="donoPetInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${donoPetInstance.id}">${fieldValue(bean: donoPetInstance, field: "nome")}</g:link></td>
					
						<td>${fieldValue(bean: donoPetInstance, field: "cpf")}</td>
					
						<td>${fieldValue(bean: donoPetInstance, field: "telefone")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${donoPetInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

PetsLife/grails-app/views/donoPet/show.gsp
<%@ page import="petslife.DonoPet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoPet.label', default: 'DonoPet')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-donoPet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-donoPet" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list donoPet">
			
				<g:if test="${donoPetInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="donoPet.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${donoPetInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${donoPetInstance?.cpf}">
				<li class="fieldcontain">
					<span id="cpf-label" class="property-label"><g:message code="donoPet.cpf.label" default="Cpf" /></span>
					
						<span class="property-value" aria-labelledby="cpf-label"><g:fieldValue bean="${donoPetInstance}" field="cpf"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${donoPetInstance?.telefone}">
				<li class="fieldcontain">
					<span id="telefone-label" class="property-label"><g:message code="donoPet.telefone.label" default="Telefone" /></span>
					
						<span class="property-value" aria-labelledby="telefone-label"><g:fieldValue bean="${donoPetInstance}" field="telefone"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:donoPetInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${donoPetInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>