PetsLife/grails-app/domain/petslife/Medico.groovy
package petslife

class Medico {
    String nome
    String cpf
    String diploma
    int idade
    int telefone
    int rg
    
    static constraints = {
        nome nullabel:false, blank: false, maxSize:35
        cpf cpf:true, unique:true        
        rg rg:true, unique:true
        telefone telefone:true, unique:true
    }
    
    String toString(){
        nome
    }
}

PetsLife/grails-app/controllers/petslife/MedicoController.groovy
package petslife



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import org.springframework.security.access.annotation.Secured
@Secured('isFullyAuthenticated()')

@Transactional(readOnly = true)
class MedicoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Medico.list(params), model:[medicoInstanceCount: Medico.count()]
    }

    def show(Medico medicoInstance) {
        respond medicoInstance
    }

    def create() {
        respond new Medico(params)
    }

    @Transactional
    def save(Medico medicoInstance) {
        if (medicoInstance == null) {
            notFound()
            return
        }

        if (medicoInstance.hasErrors()) {
            respond medicoInstance.errors, view:'create'
            return
        }

        medicoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'medico.label', default: 'Medico'), medicoInstance.id])
                redirect medicoInstance
            }
            '*' { respond medicoInstance, [status: CREATED] }
        }
    }

    def edit(Medico medicoInstance) {
        respond medicoInstance
    }

    @Transactional
    def update(Medico medicoInstance) {
        if (medicoInstance == null) {
            notFound()
            return
        }

        if (medicoInstance.hasErrors()) {
            respond medicoInstance.errors, view:'edit'
            return
        }

        medicoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Medico.label', default: 'Medico'), medicoInstance.id])
                redirect medicoInstance
            }
            '*'{ respond medicoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Medico medicoInstance) {

        if (medicoInstance == null) {
            notFound()
            return
        }

        medicoInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Medico.label', default: 'Medico'), medicoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'medico.label', default: 'Medico'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

PetsLife/grails-app/views/medico/_form.gsp
<%@ page import="petslife.Medico" %>



<div class="fieldcontain ${hasErrors(bean: medicoInstance, field: 'nome', 'error')} required">
	<label for="nome">
		<g:message code="medico.nome.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nome" maxlength="35" required="" value="${medicoInstance?.nome}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: medicoInstance, field: 'cpf', 'error')} required">
	<label for="cpf">
		<g:message code="medico.cpf.label" default="Cpf" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="cpf" required="" value="${medicoInstance?.cpf}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: medicoInstance, field: 'rg', 'error')} required">
	<label for="rg">
		<g:message code="medico.rg.label" default="Rg" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="rg" type="number" value="${medicoInstance.rg}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: medicoInstance, field: 'telefone', 'error')} required">
	<label for="telefone">
		<g:message code="medico.telefone.label" default="Telefone" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="telefone" type="number" value="${medicoInstance.telefone}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: medicoInstance, field: 'diploma', 'error')} required">
	<label for="diploma">
		<g:message code="medico.diploma.label" default="Diploma" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="diploma" required="" value="${medicoInstance?.diploma}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: medicoInstance, field: 'idade', 'error')} required">
	<label for="idade">
		<g:message code="medico.idade.label" default="Idade" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="idade" type="number" value="${medicoInstance.idade}" required=""/>

</div>

PetsLife/grails-app/views/medico/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medico.label', default: 'Medico')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-medico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-medico" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${medicoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${medicoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:medicoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

PetsLife/grails-app/views/medico/edit.gsp
<%@ page import="petslife.Medico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medico.label', default: 'Medico')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-medico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-medico" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${medicoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${medicoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:medicoInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${medicoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

PetsLife/grails-app/views/medico/index.gsp
<%@ page import="petslife.Medico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medico.label', default: 'Medico')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-medico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-medico" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nome" title="${message(code: 'medico.nome.label', default: 'Nome')}" />
					
						<g:sortableColumn property="cpf" title="${message(code: 'medico.cpf.label', default: 'Cpf')}" />
					
						<g:sortableColumn property="rg" title="${message(code: 'medico.rg.label', default: 'Rg')}" />
					
						<g:sortableColumn property="telefone" title="${message(code: 'medico.telefone.label', default: 'Telefone')}" />
					
						<g:sortableColumn property="diploma" title="${message(code: 'medico.diploma.label', default: 'Diploma')}" />
					
						<g:sortableColumn property="idade" title="${message(code: 'medico.idade.label', default: 'Idade')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${medicoInstanceList}" status="i" var="medicoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${medicoInstance.id}">${fieldValue(bean: medicoInstance, field: "nome")}</g:link></td>
					
						<td>${fieldValue(bean: medicoInstance, field: "cpf")}</td>
					
						<td>${fieldValue(bean: medicoInstance, field: "rg")}</td>
					
						<td>${fieldValue(bean: medicoInstance, field: "telefone")}</td>
					
						<td>${fieldValue(bean: medicoInstance, field: "diploma")}</td>
					
						<td>${fieldValue(bean: medicoInstance, field: "idade")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${medicoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

PetsLife/grails-app/views/medico/show.gsp
<%@ page import="petslife.Medico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medico.label', default: 'Medico')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-medico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-medico" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list medico">
			
				<g:if test="${medicoInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="medico.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${medicoInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${medicoInstance?.cpf}">
				<li class="fieldcontain">
					<span id="cpf-label" class="property-label"><g:message code="medico.cpf.label" default="Cpf" /></span>
					
						<span class="property-value" aria-labelledby="cpf-label"><g:fieldValue bean="${medicoInstance}" field="cpf"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${medicoInstance?.rg}">
				<li class="fieldcontain">
					<span id="rg-label" class="property-label"><g:message code="medico.rg.label" default="Rg" /></span>
					
						<span class="property-value" aria-labelledby="rg-label"><g:fieldValue bean="${medicoInstance}" field="rg"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${medicoInstance?.telefone}">
				<li class="fieldcontain">
					<span id="telefone-label" class="property-label"><g:message code="medico.telefone.label" default="Telefone" /></span>
					
						<span class="property-value" aria-labelledby="telefone-label"><g:fieldValue bean="${medicoInstance}" field="telefone"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${medicoInstance?.diploma}">
				<li class="fieldcontain">
					<span id="diploma-label" class="property-label"><g:message code="medico.diploma.label" default="Diploma" /></span>
					
						<span class="property-value" aria-labelledby="diploma-label"><g:fieldValue bean="${medicoInstance}" field="diploma"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${medicoInstance?.idade}">
				<li class="fieldcontain">
					<span id="idade-label" class="property-label"><g:message code="medico.idade.label" default="Idade" /></span>
					
						<span class="property-value" aria-labelledby="idade-label"><g:fieldValue bean="${medicoInstance}" field="idade"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:medicoInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${medicoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>