PetsLife/grails-app/domain/petslife/DonoClinica.groovy
package petslife

class DonoClinica {
    String nome
    String cpf
    String senha
    String email
    int telefone
    int rg
    
    static constraints = {
        nome nullabel:false, blank: false, maxSize:35
        email email:true, unique:true
        senha size: 8..12
    }
   
    String toString(){
        nome
    }
    
}

PetsLife/grails-app/controllers/petslife/DonoClinicaController.groovy
package petslife



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import org.springframework.security.access.annotation.Secured
@Secured('isFullyAuthenticated()')

@Transactional(readOnly = true)
class DonoClinicaController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond DonoClinica.list(params), model:[donoClinicaInstanceCount: DonoClinica.count()]
    }

    def show(DonoClinica donoClinicaInstance) {
        respond donoClinicaInstance
    }

    def create() {
        respond new DonoClinica(params)
    }

    @Transactional
    def save(DonoClinica donoClinicaInstance) {
        if (donoClinicaInstance == null) {
            notFound()
            return
        }

        if (donoClinicaInstance.hasErrors()) {
            respond donoClinicaInstance.errors, view:'create'
            return
        }

        donoClinicaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'donoClinica.label', default: 'DonoClinica'), donoClinicaInstance.id])
                redirect donoClinicaInstance
            }
            '*' { respond donoClinicaInstance, [status: CREATED] }
        }
    }

    def edit(DonoClinica donoClinicaInstance) {
        respond donoClinicaInstance
    }

    @Transactional
    def update(DonoClinica donoClinicaInstance) {
        if (donoClinicaInstance == null) {
            notFound()
            return
        }

        if (donoClinicaInstance.hasErrors()) {
            respond donoClinicaInstance.errors, view:'edit'
            return
        }

        donoClinicaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'DonoClinica.label', default: 'DonoClinica'), donoClinicaInstance.id])
                redirect donoClinicaInstance
            }
            '*'{ respond donoClinicaInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(DonoClinica donoClinicaInstance) {

        if (donoClinicaInstance == null) {
            notFound()
            return
        }

        donoClinicaInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'DonoClinica.label', default: 'DonoClinica'), donoClinicaInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'donoClinica.label', default: 'DonoClinica'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

PetsLife/grails-app/views/donoClinica/_form.gsp
<%@ page import="petslife.DonoClinica" %>



<div class="fieldcontain ${hasErrors(bean: donoClinicaInstance, field: 'nome', 'error')} required">
	<label for="nome">
		<g:message code="donoClinica.nome.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nome" maxlength="35" required="" value="${donoClinicaInstance?.nome}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: donoClinicaInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="donoClinica.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="email" name="email" required="" value="${donoClinicaInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: donoClinicaInstance, field: 'senha', 'error')} required">
	<label for="senha">
		<g:message code="donoClinica.senha.label" default="Senha" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="senha" maxlength="12" required="" value="${donoClinicaInstance?.senha}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: donoClinicaInstance, field: 'cpf', 'error')} required">
	<label for="cpf">
		<g:message code="donoClinica.cpf.label" default="Cpf" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="cpf" required="" value="${donoClinicaInstance?.cpf}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: donoClinicaInstance, field: 'rg', 'error')} required">
	<label for="rg">
		<g:message code="donoClinica.rg.label" default="Rg" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="rg" type="number" value="${donoClinicaInstance.rg}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: donoClinicaInstance, field: 'telefone', 'error')} required">
	<label for="telefone">
		<g:message code="donoClinica.telefone.label" default="Telefone" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="telefone" type="number" value="${donoClinicaInstance.telefone}" required=""/>

</div>

PetsLife/grails-app/views/donoClinica/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoClinica.label', default: 'DonoClinica')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-donoClinica" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-donoClinica" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${donoClinicaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${donoClinicaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:donoClinicaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

PetsLife/grails-app/views/donoClinica/edit.gsp
<%@ page import="petslife.DonoClinica" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoClinica.label', default: 'DonoClinica')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-donoClinica" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-donoClinica" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${donoClinicaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${donoClinicaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:donoClinicaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${donoClinicaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

PetsLife/grails-app/views/donoClinica/index.gsp
<%@ page import="petslife.DonoClinica" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoClinica.label', default: 'DonoClinica')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-donoClinica" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-donoClinica" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nome" title="${message(code: 'donoClinica.nome.label', default: 'Nome')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'donoClinica.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="senha" title="${message(code: 'donoClinica.senha.label', default: 'Senha')}" />
					
						<g:sortableColumn property="cpf" title="${message(code: 'donoClinica.cpf.label', default: 'Cpf')}" />
					
						<g:sortableColumn property="rg" title="${message(code: 'donoClinica.rg.label', default: 'Rg')}" />
					
						<g:sortableColumn property="telefone" title="${message(code: 'donoClinica.telefone.label', default: 'Telefone')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${donoClinicaInstanceList}" status="i" var="donoClinicaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${donoClinicaInstance.id}">${fieldValue(bean: donoClinicaInstance, field: "nome")}</g:link></td>
					
						<td>${fieldValue(bean: donoClinicaInstance, field: "email")}</td>
					
						<td>${fieldValue(bean: donoClinicaInstance, field: "senha")}</td>
					
						<td>${fieldValue(bean: donoClinicaInstance, field: "cpf")}</td>
					
						<td>${fieldValue(bean: donoClinicaInstance, field: "rg")}</td>
					
						<td>${fieldValue(bean: donoClinicaInstance, field: "telefone")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${donoClinicaInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

PetsLife/grails-app/views/donoClinica/show.gsp
<%@ page import="petslife.DonoClinica" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'donoClinica.label', default: 'DonoClinica')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-donoClinica" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-donoClinica" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list donoClinica">
			
				<g:if test="${donoClinicaInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="donoClinica.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${donoClinicaInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${donoClinicaInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="donoClinica.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${donoClinicaInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${donoClinicaInstance?.senha}">
				<li class="fieldcontain">
					<span id="senha-label" class="property-label"><g:message code="donoClinica.senha.label" default="Senha" /></span>
					
						<span class="property-value" aria-labelledby="senha-label"><g:fieldValue bean="${donoClinicaInstance}" field="senha"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${donoClinicaInstance?.cpf}">
				<li class="fieldcontain">
					<span id="cpf-label" class="property-label"><g:message code="donoClinica.cpf.label" default="Cpf" /></span>
					
						<span class="property-value" aria-labelledby="cpf-label"><g:fieldValue bean="${donoClinicaInstance}" field="cpf"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${donoClinicaInstance?.rg}">
				<li class="fieldcontain">
					<span id="rg-label" class="property-label"><g:message code="donoClinica.rg.label" default="Rg" /></span>
					
						<span class="property-value" aria-labelledby="rg-label"><g:fieldValue bean="${donoClinicaInstance}" field="rg"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${donoClinicaInstance?.telefone}">
				<li class="fieldcontain">
					<span id="telefone-label" class="property-label"><g:message code="donoClinica.telefone.label" default="Telefone" /></span>
					
						<span class="property-value" aria-labelledby="telefone-label"><g:fieldValue bean="${donoClinicaInstance}" field="telefone"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:donoClinicaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${donoClinicaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>